#!/bin/bash

set -e

CATALINA_HOME=/usr/share/tomcat8
TOMCAT_VERSION=8.5.32

# Check whether there exists a valid instance
# of Tomcat8 installed at the specified directory
[[ -d $CATALINA_HOME ]] && { service tomcat8 status; } && {
    echo "Tomcat8 is already installed at $CATALINA_HOME. Skip reinstalling it."
    exit 0
}

# Clear install directory
if [ -d $CATALINA_HOME ]; then
    rm -rf $CATALINA_HOME
fi
mkdir -p $CATALINA_HOME

# Download the latest Tomcat8 version
sudo yum install -y tomcat8 

# Create the service init.d script
cat > /etc/init.d/tomcat8 <<'EOF'
#!/bin/bash
# description: Tomcat8 Start Stop Restart
# processname: tomcat8
PATH=$JAVA_HOME/bin:$PATH
export PATH
CATALINA_HOME='/usr/share/tomcat8'

case $1 in
start)
sh $CATALINA_HOME/bin/startup.sh
;;
stop)
sh $CATALINA_HOME/bin/shutdown.sh
;;
restart)
sh $CATALINA_HOME/bin/shutdown.sh
sh $CATALINA_HOME/bin/startup.sh
;;
esac
exit 0
EOF

# Change permission mode for the service script
chmod 755 /etc/init.d/tomcat8

